# Sidebar navigation

- label: 'Introduction'
  link: '/docs'
- label: 'Getting started'
  link: '/docs/getting-started'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/docs/usage/creating-docs'
    - label: 'Navigation'
      link: '/docs/usage/navigation'
    - label: 'Shadowing'
      link: '/docs/usage/shadowing'
