name: Deploy Develop to Netlify
on:
  push:
    branches:
      - develop
  repository_dispatch:
    types: [advo-deploy-develop]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
      with:
        ref: develop
    - name: Update submodules
      run: git submodule update --init --remote

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Yarn
      run: sudo npm -g install yarn
    - name: Set yarn cache directory
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Yarn install
      run: yarn install --frozen-lockfile
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}

    - name: gatsby build
      run: npm run build
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        ALGOLIA_API_KEY:  ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_APP_ID:  ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_INDEX_NAME:  ${{ secrets.ALGOLIA_INDEX_NAME }}

    - name: Netlify Deploy
      run: |
        sudo npm -g install netlify-cli
        netlify deploy --dir=public --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEVELOP_SITE_ID }}
