name: Deploy Develop to Netlify on Push
on:
  push:
    branches:
      - eb-netlify
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # https://github.com/actions/setup-node#usage
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: git submodule update --init --remote
    - run: npm install
    - run: npm run build
    # Deploy the gatsby build to Netlify
    #- run: npx netlify-cli deploy --dir=public --prod
    # https://github.com/netlify/actions/blob/master/cli/README.md
    - uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepswithargs
        args: deploy --dir=public --prod
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
